discount: 0.99
rewards:
  '[0, 1]': 1
  '[0, 2]': -1
  '[0, 5]': 1
  '[1, 0]': 1
  '[1, 3]': -1
  '[1, 6]': 1
  '[2, 1]': 1
  '[2, 7]': 1
  '[3, 2]': -1
  '[3, 5]': 1
  '[3, 7]': 1
  '[3, 8]': 1
  '[4, 7]': -1
  '[5, 1]': 1
  '[5, 3]': -1
  '[6, 1]': -1
  '[6, 2]': 1
  '[6, 4]': -1
  '[7, 0]': 1
  '[7, 4]': -1
  '[7, 5]': 1
  '[7, 6]': -1
  '[7, 8]': -1
  '[8, 0]': 1
  '[8, 1]': 1
  '[8, 6]': 1
  '[8, 7]': 1
size:
- 9
- 9
terminal_states: []
transition_prob: 0.8
walls:
- - 0
  - 7
- - 5
  - 7
- - 5
  - 4
- - 3
  - 6
- - 0
  - 2
- - 6
  - 4
- - 4
  - 0
- - 5
  - 3
white_reward: -0.04
