discount: 0.99
rewards:
  '[0, 0]': 1
  '[1, 1]': -1
  '[1, 3]': -1
  '[1, 4]': -1
  '[1, 6]': -1
  '[2, 1]': -1
  '[3, 3]': 1
  '[3, 5]': 1
  '[4, 0]': -1
  '[4, 3]': 1
  '[4, 4]': 1
  '[5, 0]': -1
  '[5, 3]': 1
  '[5, 4]': -1
  '[5, 6]': -1
  '[6, 2]': 1
size:
- 7
- 7
terminal_states: []
transition_prob: 0.8
walls:
- - 2
  - 5
- - 4
  - 0
- - 6
  - 3
- - 1
  - 4
- - 1
  - 3
- - 1
  - 5
white_reward: -0.04
