discount: 0.99
rewards:
  '[0, 4]': -1
  '[0, 6]': -1
  '[1, 0]': -1
  '[1, 2]': -1
  '[1, 7]': -1
  '[1, 8]': 1
  '[2, 0]': -1
  '[2, 3]': 1
  '[2, 4]': 1
  '[2, 7]': 1
  '[2, 8]': -1
  '[3, 0]': -1
  '[3, 8]': 1
  '[4, 0]': 1
  '[4, 7]': -1
  '[5, 0]': 1
  '[5, 6]': 1
  '[5, 7]': 1
  '[6, 0]': 1
  '[6, 1]': -1
  '[7, 0]': 1
  '[7, 6]': 1
  '[7, 8]': -1
  '[8, 5]': 1
  '[8, 6]': -1
  '[8, 7]': -1
  '[8, 8]': 1
size:
- 9
- 9
terminal_states: []
transition_prob: 0.8
walls:
- - 8
  - 1
- - 8
  - 5
- - 3
  - 7
- - 6
  - 8
- - 2
  - 0
- - 6
  - 3
- - 4
  - 4
- - 6
  - 0
white_reward: -0.04
