discount: 0.99
rewards:
  '[0, 0]': -1
  '[0, 10]': -1
  '[0, 12]': -1
  '[0, 13]': -1
  '[0, 15]': -1
  '[0, 4]': 1
  '[0, 8]': 1
  '[1, 0]': -1
  '[1, 11]': -1
  '[1, 13]': -1
  '[1, 2]': -1
  '[1, 3]': -1
  '[1, 5]': -1
  '[1, 6]': 1
  '[1, 7]': 1
  '[10, 0]': 1
  '[10, 10]': -1
  '[10, 11]': 1
  '[10, 7]': -1
  '[10, 9]': 1
  '[11, 10]': -1
  '[11, 14]': 1
  '[11, 16]': -1
  '[11, 4]': 1
  '[11, 6]': -1
  '[11, 8]': -1
  '[12, 0]': 1
  '[12, 12]': 1
  '[12, 15]': -1
  '[12, 4]': -1
  '[12, 5]': 1
  '[12, 6]': 1
  '[13, 0]': 1
  '[13, 11]': -1
  '[13, 16]': 1
  '[13, 5]': 1
  '[14, 5]': 1
  '[14, 9]': -1
  '[15, 10]': -1
  '[15, 12]': 1
  '[15, 14]': -1
  '[15, 2]': 1
  '[15, 3]': -1
  '[16, 10]': 1
  '[16, 2]': -1
  '[16, 5]': 1
  '[16, 6]': 1
  '[16, 8]': 1
  '[2, 0]': -1
  '[2, 10]': 1
  '[2, 11]': 1
  '[2, 1]': -1
  '[2, 4]': 1
  '[2, 7]': -1
  '[3, 0]': 1
  '[3, 12]': 1
  '[3, 15]': -1
  '[3, 16]': 1
  '[3, 5]': 1
  '[3, 8]': -1
  '[4, 12]': -1
  '[4, 16]': -1
  '[4, 1]': -1
  '[4, 4]': 1
  '[4, 6]': -1
  '[5, 13]': 1
  '[5, 1]': 1
  '[5, 3]': -1
  '[5, 5]': -1
  '[5, 7]': 1
  '[5, 8]': 1
  '[5, 9]': -1
  '[6, 0]': -1
  '[6, 16]': 1
  '[6, 1]': 1
  '[6, 2]': 1
  '[6, 3]': -1
  '[6, 5]': 1
  '[6, 6]': 1
  '[6, 7]': 1
  '[7, 0]': 1
  '[7, 13]': -1
  '[7, 15]': 1
  '[7, 8]': -1
  '[7, 9]': 1
  '[8, 11]': -1
  '[8, 12]': 1
  '[8, 2]': -1
  '[8, 3]': -1
  '[8, 5]': 1
  '[8, 8]': 1
  '[9, 0]': 1
  '[9, 14]': -1
  '[9, 2]': -1
  '[9, 4]': -1
  '[9, 8]': -1
size:
- 17
- 17
terminal_states: []
transition_prob: 0.8
walls:
- - 5
  - 1
- - 11
  - 0
- - 3
  - 3
- - 7
  - 15
- - 12
  - 9
- - 0
  - 5
- - 16
  - 8
- - 2
  - 10
- - 15
  - 5
- - 13
  - 11
- - 0
  - 4
- - 8
  - 15
- - 15
  - 13
- - 6
  - 12
- - 3
  - 7
- - 11
  - 1
white_reward: -0.04
