discount: 0.99
rewards:
  '[0, 11]': -1
  '[0, 12]': -1
  '[0, 1]': 1
  '[0, 3]': -1
  '[0, 5]': -1
  '[0, 6]': 1
  '[0, 7]': 1
  '[1, 0]': 1
  '[1, 12]': 1
  '[1, 1]': -1
  '[1, 4]': 1
  '[1, 5]': 1
  '[1, 7]': 1
  '[10, 5]': 1
  '[11, 10]': 1
  '[11, 7]': 1
  '[11, 9]': -1
  '[12, 9]': 1
  '[2, 12]': 1
  '[2, 3]': 1
  '[2, 7]': 1
  '[2, 8]': -1
  '[2, 9]': 1
  '[3, 0]': 1
  '[3, 10]': -1
  '[3, 12]': -1
  '[3, 6]': -1
  '[3, 8]': 1
  '[3, 9]': 1
  '[4, 11]': -1
  '[4, 12]': -1
  '[4, 3]': -1
  '[4, 8]': 1
  '[5, 3]': 1
  '[5, 5]': 1
  '[5, 6]': -1
  '[5, 8]': 1
  '[5, 9]': -1
  '[6, 11]': 1
  '[6, 2]': 1
  '[6, 3]': 1
  '[6, 6]': -1
  '[6, 7]': 1
  '[7, 3]': 1
  '[7, 7]': 1
  '[7, 9]': 1
  '[8, 11]': -1
  '[8, 6]': -1
  '[8, 9]': -1
  '[9, 0]': -1
  '[9, 1]': 1
  '[9, 2]': 1
  '[9, 4]': -1
  '[9, 7]': 1
  '[9, 8]': -1
  '[9, 9]': 1
size:
- 13
- 13
terminal_states: []
transition_prob: 0.8
walls:
- - 6
  - 2
- - 1
  - 11
- - 8
  - 6
- - 8
  - 1
- - 8
  - 7
- - 12
  - 11
- - 11
  - 0
- - 11
  - 8
- - 11
  - 3
- - 6
  - 9
- - 3
  - 1
- - 9
  - 10
white_reward: -0.04
