discount: 0.99
rewards:
  '[0, 2]': 1
  '[0, 5]': 1
  '[1, 0]': -1
  '[1, 10]': 1
  '[1, 2]': -1
  '[1, 3]': 1
  '[10, 10]': 1
  '[10, 7]': 1
  '[2, 0]': 1
  '[2, 1]': 1
  '[2, 3]': 1
  '[2, 7]': 1
  '[3, 2]': -1
  '[3, 6]': -1
  '[4, 0]': -1
  '[4, 10]': -1
  '[4, 1]': 1
  '[4, 4]': 1
  '[4, 5]': 1
  '[4, 7]': -1
  '[5, 1]': -1
  '[5, 6]': -1
  '[5, 7]': -1
  '[5, 8]': -1
  '[6, 10]': 1
  '[6, 5]': -1
  '[6, 7]': 1
  '[7, 1]': 1
  '[7, 9]': -1
  '[8, 10]': 1
  '[8, 1]': 1
  '[8, 2]': -1
  '[8, 3]': -1
  '[8, 5]': 1
  '[8, 6]': 1
  '[9, 0]': -1
  '[9, 10]': 1
  '[9, 2]': 1
  '[9, 3]': 1
  '[9, 9]': 1
size:
- 11
- 11
terminal_states: []
transition_prob: 0.8
walls:
- - 1
  - 3
- - 1
  - 8
- - 4
  - 3
- - 3
  - 10
- - 9
  - 5
- - 3
  - 4
- - 9
  - 1
- - 0
  - 9
- - 6
  - 0
- - 7
  - 4
white_reward: -0.04
