discount: 0.99
rewards:
  '[0, 1]': 1
  '[0, 3]': -1
  '[0, 4]': 1
  '[0, 5]': 1
  '[0, 6]': 1
  '[0, 8]': -1
  '[0, 9]': -1
  '[1, 3]': 1
  '[1, 4]': -1
  '[1, 9]': -1
  '[10, 2]': 1
  '[10, 5]': 1
  '[10, 7]': -1
  '[2, 0]': -1
  '[2, 2]': -1
  '[2, 8]': -1
  '[3, 2]': 1
  '[3, 5]': -1
  '[3, 9]': 1
  '[4, 1]': 1
  '[4, 5]': 1
  '[4, 6]': -1
  '[4, 8]': -1
  '[4, 9]': 1
  '[5, 0]': 1
  '[5, 10]': -1
  '[5, 8]': 1
  '[5, 9]': -1
  '[6, 0]': -1
  '[6, 3]': -1
  '[6, 4]': -1
  '[6, 6]': -1
  '[7, 2]': 1
  '[7, 3]': 1
  '[7, 6]': 1
  '[7, 7]': 1
  '[8, 1]': 1
  '[8, 8]': 1
  '[9, 10]': -1
  '[9, 8]': -1
size:
- 11
- 11
terminal_states: []
transition_prob: 0.8
walls:
- - 6
  - 0
- - 5
  - 4
- - 6
  - 4
- - 9
  - 0
- - 4
  - 0
- - 2
  - 10
- - 2
  - 1
- - 9
  - 5
- - 7
  - 7
- - 7
  - 2
white_reward: -0.04
