discount: 0.99
rewards:
  '[1, 2]': 1
  '[2, 0]': 1
  '[2, 4]': 1
  '[2, 5]': 1
  '[3, 0]': 1
  '[3, 1]': -1
  '[3, 5]': 1
  '[4, 0]': -1
  '[4, 1]': 1
  '[4, 6]': 1
  '[5, 1]': 1
  '[5, 2]': -1
  '[5, 6]': -1
  '[6, 1]': -1
  '[6, 4]': -1
  '[6, 5]': 1
size:
- 7
- 7
terminal_states: []
transition_prob: 0.8
walls:
- - 4
  - 3
- - 3
  - 2
- - 3
  - 0
- - 0
  - 1
- - 3
  - 5
- - 6
  - 2
white_reward: -0.04
