discount: 0.99
rewards:
  '[0, 0]': 1
  '[0, 12]': 1
  '[0, 13]': 1
  '[0, 2]': 1
  '[0, 5]': -1
  '[1, 12]': -1
  '[1, 13]': 1
  '[1, 14]': -1
  '[1, 4]': 1
  '[1, 8]': 1
  '[10, 4]': 1
  '[10, 5]': -1
  '[10, 8]': -1
  '[11, 0]': -1
  '[11, 11]': -1
  '[11, 4]': 1
  '[12, 10]': -1
  '[12, 11]': -1
  '[12, 12]': 1
  '[12, 13]': -1
  '[12, 1]': 1
  '[12, 4]': 1
  '[12, 5]': 1
  '[13, 10]': -1
  '[13, 11]': -1
  '[13, 12]': -1
  '[13, 1]': 1
  '[13, 3]': 1
  '[13, 4]': -1
  '[13, 6]': -1
  '[13, 7]': 1
  '[14, 5]': -1
  '[14, 6]': -1
  '[14, 8]': -1
  '[2, 13]': 1
  '[2, 2]': -1
  '[2, 3]': -1
  '[2, 4]': -1
  '[2, 5]': 1
  '[2, 6]': -1
  '[3, 0]': 1
  '[3, 12]': -1
  '[3, 13]': -1
  '[3, 1]': 1
  '[3, 4]': 1
  '[3, 6]': 1
  '[3, 9]': 1
  '[4, 0]': -1
  '[4, 10]': -1
  '[4, 11]': 1
  '[4, 13]': 1
  '[4, 2]': -1
  '[4, 4]': -1
  '[4, 9]': 1
  '[5, 14]': 1
  '[5, 1]': 1
  '[5, 3]': -1
  '[5, 4]': 1
  '[5, 5]': -1
  '[6, 0]': -1
  '[6, 12]': -1
  '[6, 3]': 1
  '[6, 4]': 1
  '[6, 5]': -1
  '[6, 8]': -1
  '[6, 9]': 1
  '[7, 12]': -1
  '[7, 1]': 1
  '[7, 4]': 1
  '[7, 9]': -1
  '[8, 12]': -1
  '[8, 6]': 1
  '[9, 1]': -1
  '[9, 3]': -1
  '[9, 6]': -1
size:
- 15
- 15
terminal_states: []
transition_prob: 0.8
walls:
- - 3
  - 14
- - 11
  - 0
- - 12
  - 8
- - 1
  - 8
- - 5
  - 4
- - 0
  - 7
- - 4
  - 3
- - 1
  - 2
- - 7
  - 2
- - 1
  - 1
- - 6
  - 9
- - 3
  - 6
- - 9
  - 1
- - 4
  - 1
white_reward: -0.04
