discount: 0.99
rewards:
  '[0, 0]': 1
  '[0, 2]': -1
  '[0, 4]': -1
  '[0, 9]': -1
  '[1, 12]': 1
  '[1, 2]': -1
  '[1, 3]': 1
  '[1, 6]': 1
  '[1, 9]': -1
  '[10, 11]': -1
  '[10, 2]': 1
  '[10, 4]': -1
  '[10, 6]': 1
  '[10, 9]': -1
  '[11, 0]': 1
  '[11, 11]': -1
  '[11, 3]': 1
  '[11, 7]': 1
  '[11, 9]': 1
  '[12, 0]': 1
  '[12, 10]': -1
  '[12, 12]': 1
  '[2, 10]': 1
  '[2, 1]': 1
  '[2, 8]': 1
  '[3, 0]': 1
  '[3, 10]': 1
  '[3, 12]': -1
  '[3, 1]': 1
  '[3, 4]': -1
  '[3, 8]': -1
  '[4, 4]': 1
  '[4, 5]': 1
  '[4, 8]': -1
  '[5, 0]': -1
  '[5, 12]': 1
  '[5, 3]': 1
  '[5, 5]': 1
  '[5, 8]': 1
  '[6, 10]': -1
  '[6, 11]': -1
  '[6, 12]': -1
  '[6, 5]': 1
  '[6, 7]': -1
  '[6, 9]': -1
  '[7, 11]': 1
  '[7, 5]': -1
  '[7, 6]': -1
  '[8, 10]': 1
  '[8, 1]': -1
  '[9, 11]': -1
  '[9, 1]': -1
  '[9, 2]': 1
  '[9, 4]': 1
  '[9, 7]': 1
  '[9, 8]': 1
size:
- 13
- 13
terminal_states: []
transition_prob: 0.8
walls:
- - 3
  - 9
- - 5
  - 0
- - 6
  - 10
- - 11
  - 12
- - 8
  - 12
- - 9
  - 3
- - 0
  - 2
- - 3
  - 5
- - 5
  - 12
- - 5
  - 5
- - 3
  - 6
- - 12
  - 10
white_reward: -0.04
