discount: 0.99
rewards:
  '[1, 0]': -1
  '[1, 1]': -1
  '[2, 0]': 1
  '[2, 3]': -1
  '[3, 1]': 1
size:
- 4
- 4
terminal_states: []
transition_prob: 0.8
walls:
- - 1
  - 3
- - 3
  - 2
- - 0
  - 3
white_reward: -0.04
